url: https://y7kim.github.io
baseurl: 

title: PEP
email: pep@enpc.org
description: "La Junior-Entreprise des Ponts"

social:
  - title: linkedin
    url: http://www.linkedin.com/company/ponts-etudes-projets/
  - title: twitter
    url: http://twitter.com/pontsetudes

address:
  - line: 6-8 boulevard Copernic
  - line: Champs-sur-Marne
  - line: 77455 Marne-la-Vallée CEDEX 2

plugins:
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
    - width: 400  # [Required] How wide the resized image will be. # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
  auto_rotate: false
  strip: false
  base_path: uploads
  output_path_format: assets/resized/%{width}/%{basename}
  save_to_source: false
  cache: false
  extra_images:
    - uploads/*/*/*/*.{jpeg,jpg}

competences:
  - title: Mathématiques et <br> Informatique
    slug: math-info
    thumbnail: imi-thumbnail.jpg
    img: imi.jpg
    description: L’informatique est au cœur de la formation dispensée aux Ponts dès la première année, prolongée par un master en ingénierie mathématique et informatique. La formation généraliste de l’école permet en outre aux étudiants d’adopter une approche globale face à un problème informatique, et ainsi de réaliser vos projets les plus pointus.
  - title: Génie Civil <br> et Mécanique
    slug: genie-civil-mecanique
    thumbnail: bridge-millau-thumbnail.jpg
    img: gcc.jpg
    description: Forte de plus de 250 ans d’expérience dans le génie civil et mécanique, l’école des Ponts ParisTech forme encore aujourd’hui des ingénieurs à la pointe de ce domaine.
  - title: Énergie, Transports <br> et Aménagements
    slug: energies-transports-amenagements
    thumbnail: vet-thumbnail.jpg
    img: vet.jpg
    description: Evaluer une empreinte carbone, mener une politique de transports à grande échelle, aménager des zones urbaines font parti des enseignements des étudiants du département Ville, environnement, transports de l’école. Ponts Études Projets, en accord avec les efforts mis en place par l’école pour conforter sa place de leader dans les domaines de développement durable et d’urbanisme, s’engage dans ces activités essentielles
  - title: Stratégie, Finance <br> et Économie
    slug: strategie-finance-economie
    thumbnail: segf-thumbnail.jpg
    img: segf.jpg
    description: L’École des Ponts ParisTech est également très réputée dans les domaines de la finance et de l’économie, et forme de nombreux consultants et analystes. Chaque année, plus d’un tiers des étudiants quittent l’école pour le monde de l’économie, de la finance, de la stratégie ou du conseil.
  - title: Génie Industriel <br> et Marketing
    slug: genie-industriel
    thumbnail: gi-thumbnail.jpg
    img: gi.jpg
    description: Avant-gardiste dans le domaine, l’école des Ponts ParisTech s’est adaptée aux grands enjeux de la mondialisation et possède un département de génie industriel où sont formés des spécialistes de la supply chain, des enjeux globaux et de l’innovation de rupture.
  - title: Traduction <br> Technique
    slug: traduction-technique
    thumbnail: trad-thumbnail.jpg
    img: trad.jpg
    description: Ponts Etudes Projets, avec son cortège d’élèves étrangers (40% de la promotion), est à même de traduire tout document technique dans plus de 15 langues différentes !

# Build settings
markdown: kramdown
permalink: pretty