url: https://y7kim.github.io
baseurl: 

# Site settings
title: PEP
email: pep@enpc.org
description: "La Junior-Entreprise des Ponts"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/company/ponts-etudes-projets/
  - title: twitter
    url: http://twitter.com/pontsetudes

# Postal address (add as many lines as necessary)
address:
  - line: 6-8 boulevard Copernic
  - line: Champs-sur-Marne
  - line: 77455 Marne-la-Vallée CEDEX 2

competences:
- title: Mathématiques et Informatique
  url: math-info/
  img: imi.jpg
  thumbnail: imi-thumbnail.jpg
  description: Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse.
- title: Génie Civil et Mécanique
  url: genie-civil/
  img: gcc.jpg
  thumbnail: gcc-thumbnail.jpg
  description: Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse.

# Build settings
markdown: kramdown
permalink: pretty