url: https://y7kim.github.io
baseurl: 

# Site settings
title: PEP
email: pep@enpc.org
description: "La Junior-Entreprise des Ponts"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/company/ponts-etudes-projets/
  - title: twitter
    url: http://twitter.com/pontsetudes

# Postal address (add as many lines as necessary)
address:
  - line: 6-8 boulevard Copernic
  - line: Champs-sur-Marne
  - line: 77455 Marne-la-Vallée CEDEX 2

# Build settings
markdown: kramdown
permalink: pretty