url: "https://junior-pep.fr"
baseurl: 

title: Ponts Études Projets | Junior-Entreprise des Ponts
email: contact@junior-pep.fr
description: La Junior-Entreprise de l'École des Ponts est experte en génie civil, informatique et finance. Pour un site web, une traduction ou une étude de marché, contactez nos Junior-Entrepreuneurs.
logo: /img/logo.png 
lang: fr

webmaster_verifications:
  google: 1OVj379TvI6vdyrAX5gRADUMU4OTx0MHoa38vSN_gJg
  bing: 34CD8A30EF7237775F111BC751864D23

google_analytics: UA-138338484-1

author:
  twitter: antoineeudes

twitter:
  username: pontsetudes
  card: Ponts Etudes Projets

social:
  name: Ponts Etudes Projets
  links:
    - http://www.linkedin.com/company/ponts-etudes-projets/
    - https://www.facebook.com/junior.entreprise.ponts.etudes.projets
    - http://twitter.com/pontsetudes

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

networks:
  - title: linkedin
    url: http://www.linkedin.com/company/ponts-etudes-projets/
  - title: twitter
    url: http://twitter.com/pontsetudes
  - title: facebook
    url: https://www.facebook.com/junior.entreprise.ponts.etudes.projets

address:
  - line: 6-8 boulevard Copernic
  - line: Champs-sur-Marne
  - line: 77455 Marne-la-Vallée CEDEX 2

competences:
  - title: Informatique et Data Science
    slug: math-info
    thumbnail: imi-thumbnail.jpg
    img: imi.jpg
    alt: Mathématiques et Informatique
    description: L’informatique est au cœur de la formation dispensée aux Ponts dès la première année, prolongée par un master en ingénierie mathématique et informatique. La formation généraliste de l’école permet en outre aux étudiants d’adopter une approche globale face à un problème informatique, et ainsi de réaliser vos projets les plus pointus. Notre Junior-Entreprise excelle dans la conception de sites webs et de programmes en tout genre, allant du domaine de la Vision Artificielle au Machine Learning.
  - title: Génie Civil <br> et Mécanique
    slug: genie-civil-mecanique
    thumbnail: bridge-millau-thumbnail.jpg
    img: bridge-millau.jpg
    alt: Génie Civil et Mécanique
    description: Forte de plus de 250 ans d’expérience dans le génie civil et mécanique, l’École des Ponts ParisTech forme encore aujourd’hui des ingénieurs à la pointe de ce domaine. Nos Junior-Entrepreneurs seront à même de vous guider dans vos projets de dimensionnement de structures ou d'étude de marché.
  - title: Énergie, Transports <br> et Aménagements
    slug: energies-transports-amenagements
    thumbnail: vet-thumbnail.jpg
    img: vet.jpg
    alt: Énergie, Transports et Aménagements
    description: Évaluer une empreinte carbone, mener une politique de transports à grande échelle, aménager des zones urbaines font partie des enseignements des étudiants du département Ville, Environnement, Transports de l’école. Ponts Études Projets, en accord avec les efforts mis en place par l’école pour conforter sa place de leader dans les domaines de développement durable et d’urbanisme, s’engage dans ces activités essentielles.
  - title: Stratégie, Finance <br> et Économie
    slug: strategie-finance-economie
    thumbnail: segf-thumbnail.jpg
    img: segf.jpg
    alt: Stratégie, Finance et Économie
    description: L’École des Ponts ParisTech est également très réputée dans les domaines de la finance et de l’économie, et forme de nombreux consultants et analystes. Chaque année, plus d’un tiers des étudiants quittent l’école pour le monde de l’économie, de la finance, de la stratégie ou du conseil.
  - title: Génie Industriel <br> et Marketing
    slug: genie-industriel
    thumbnail: gi-thumbnail.jpg
    img: gi.jpg
    alt: Génie Industriel <br> et Marketing
    description: Avant-gardiste dans le domaine, l’école des Ponts ParisTech s’est adaptée aux grands enjeux de la mondialisation et possède un département de génie industriel où sont formés des spécialistes de la supply chain, des enjeux globaux et de l’innovation de rupture.
  - title: Traduction <br> Technique
    slug: traduction-technique
    thumbnail: trad-thumbnail.jpg
    img: trad.jpg
    alt: Traduction Technique
    description: Ponts Etudes Projets, avec son cortège d’élèves étrangers (40% de la promotion), est à même de traduire tout document technique dans plus de 15 langues différentes ! Ce rayonnement international permet à notre Junior-Entreprise de se démarquer dans les projets de Traductions Techniques.

equipe:
  - title: Président
    slug: prez
    img: prez.jpg
    alt: Président
    name: Timothé Catimel
    description: Le président est le responsable légal de la Junior-Entreprise. À l’aide du bureau, il pilote l’association et tous ses pôles. Sa mission principale est donc de veiller au bon fonctionnement de chacun de ces pôles et plus globalement de la Junior-Entreprise.
    mail: timothe.catimel@junior-pep.fr
    in: https://www.linkedin.com/in/timoth%C3%A9catimel/
  - title: Vice-Président
    slug: v-prez
    img: vprez.jpg
    alt: Vice-Président
    name: Nil Parent
    description: Le vice-président travaille main dans la main avec le président. Il élabore la stratégie annuelle et gère les partenariats. Il doit aussi s'intéresser aux différents indicateurs de performance développés par le pôle qualité et assister les autres pôles de la Junior-Entreprise.
    mail: nil.parent@junior-pep.fr
    in: https://www.linkedin.com/in/nil-parent/
  - title: Secrétaire Général
    slug: secgen
    img: secgen.jpg
    alt: Secrétaire Général
    name: Mathieu Harlay
    description: Le secrétaire général est le responsable de la gestion associative de la Junior-Entreprise. Membre du bureau, il participe au pilotage de l’association et de tous ses pôles. Il assure les tâches admi-nistratives, est responsable de la tenue des registres et veille au bon fonctionnement de l’équipe. 
    mail: mathieu.harlay@junior-pep.fr
    in: https://www.linkedin.com/in/mathieu-harlay-b096371b9/
  - title: Trésorière
    slug: trez
    img: trez.jpg
    alt: Trésorière
    name: Laëtitia Brodin
    description: Le Trésorier gère le fonctionnement financier de la Junior-Entreprise. Engageant sa responsabilité civile et légale, il planifie et surveille le budget, s'occupe des comptes bancaires, déclare les impôts de la Junior-Entreprise et vérifie la comptabilité du Vice-Trésorier.
    mail: laetitia.brodin@junior-pep.fr
    in: https://www.linkedin.com/in/la%C3%ABtitia-brodin-5a7926201/
  - title: Vice-Trésorière
    slug: vtrez
    img: vtrez.jpg
    alt: Vice-Trésorière
    name: Chloé Dujarrier
    description: Le Vice-Trésorier est l'adjoint du Trésorier de la Junior-Entreprise. Sa mission principale est de gérer la comptabilité en lien avec l’expert-comptable, de vérifier les opérations du Trésorier et de l’assister dans l’élaboration du budget. Il s’occupe aussi de l’archivage des documents.
    mail: chloe.dujarrier@junior-pep.fr
    in: https://www.linkedin.com/in/chlo%C3%A9-dujarrier-173460195/
  - title: Directeur de projet
    slug: dproj
    img: dproj.jpg
    alt: Directeur de Projet
    name: Lilian Beye
    mail: lilian.beye@junior-pep.fr
    description: Le directeur de projet est à la tête du pôle étude et s’occupe d’organiser la prospection commerciale ainsi que d’encadrer les relations client-étudiant. Il a une vue d’ensemble sur les missions en cours et s’assure de leur bon déroulé tout comme de la bonne coordination des membres de son équipe.
    in: https://www.linkedin.com/in/lilian-beye/
  - title: Chef de Projet
    slug: chef1
    img: chef1.jpg
    alt: Chef de Projet
    name: Jérémie Lecoutre
    description: Tout au long d'une étude, les chefs de projets, travaillant en binôme, sont les intermédiaires de référence entre le Client et le(s) étudiant(s) réalisateur(s) de l'étude. Ils suivent les étudiants tout au long de l'étude, du recrutement jusqu'à la clôture.
    mail: jeremie.lecoutre@junior-pep.fr
    in: https://www.linkedin.com/in/j%C3%A9r%C3%A9mie-lecoutre-620a7b1bb/
  - title: Chef de Projet
    slug: chef2
    img: chef2.jpg
    alt: Chef de Projet
    name: Quentin Gaignard
    description: Avant le début d’une étude, il est du ressort des chefs de projet de trouver les étudiants les plus qualifiés et répondant aux mieux aux exigences du Client. Les CVs et lettres de motivation des étudiants ayant répondu à l'annonce de l'étude permettent de ne garder que les meilleurs éléments.
    mail: quentin.gaignard@junior-pep.fr
    in: https://www.linkedin.com/in/quentin-gaignard-2a649b201/
  - title: Cheffe de Projet
    slug: chef3
    img: chef3.jpg
    alt: Cheffe de Projet
    name: Bao-Trân Truong
    description: Le travail du chef de projet, c'est également d'entretenir le contact entre la Junior et les entreprises. Ils sont en permanence en relation avec des chefs d'entreprises ou de départements techniques pour comprendre leurs besoins et y apporter des solutions adaptées.
    mail: bao-tran.truong@junior-pep.fr
    in: https://www.linkedin.com/in/bao-tr%C3%A2n-truong-33912420a/
  - title: Chef de Projet
    slug: chef4
    img: chef4.jpg
    alt: Chef de Projet
    name: Hector Danel
    description: Les chefs de projet transmettent les  questions des étudiants, informent sur l'avancée de la mission, proposent et organisent des réunions en présence des deux partis pour une première rencontre ou encore pour une présentation des livrables.
    mail: hactor.danel@junior-pep.fr
    in: https://www.linkedin.com/in/hector-danel-4b7aa01ba/
  - title: Responsable Qualité
    slug: quali
    img: quali.jpg
    alt: Responsable Qualité
    name: Paul Invernizzi
    description: Le Responsable Qualité s’assure du bon fonctionnement des services de la Junior Entreprise. En relisant chaque document, il s’assure de leur conformité au cadre légal. Il se charge aussi de gérer les différents indicateurs de performance qui aideront la Junior Entreprise à améliorer ses services.
    mail: paul.invernizzi@junior-pep.fr
    in: https://www.linkedin.com/in/paul-invernizzi-47439a200/
  - title: Directeur des Systèmes <br> d'Information
    slug: dsi
    img: dsi.jpg
    alt: Directeur des Systèmes d'Information
    name: Justin Capgras
    description: Le DSI s'occupe de la maintenance du site internet et de l'ensemble des moyens informatiques utilisés par les membres de la Junior et les intervenants. Il assiste aussi le responsable qualité dans la relecture des documents études.
    mail: justin.capgras@junior-pep.fr
    in: https://www.linkedin.com/in/justin-capgras-9b4570200/
  - title: Directrice communication
    slug: com
    img: com.jpg
    alt: Directrice communication
    name: Holly Healey
    description: Le Directeur Communication est responsable de l’image interne et externe de PEP. Son travail consiste à élaborer des supports de communication (visuels, goodies), entretenir une activité sur les réseaux sociaux et maintenir le lien avec les Alumni et les autres Junior-Entreprises.
    mail: holly.healey@junior-pep.fr
    in: https://www.linkedin.com/in/holly-healey/
  

# Build settings
markdown: kramdown
permalink: pretty
